### ISSUE TITLE
getting error "index out of range" while update terraform-docs

### ISSUE THREAD

**Issue by sanketg86** [cellpointmobile/vk-definitions#6]
I observed that while update terraform-docs getting below error.

```
$ vk update terraform-docs
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/cellpointmobile/vk/program.(*Command).GetLocalVersion(0xc0001b0210, 0x0, 0x0)
	/home/abo/sandbox/vk/program/command.go:47 +0x2ab
github.com/cellpointmobile/vk/program.IsLatestVersion(0xae8e60, 0xc0001b0210, 0x7fffa2b3037c)
	/home/abo/sandbox/vk/program/funcs.go:38 +0x82
github.com/cellpointmobile/vk/cmd.glob..func7(0xe81240, 0xc0000937b0, 0x1, 0x1)
	/home/abo/sandbox/vk/cmd/update.go:59 +0x51f
github.com/spf13/cobra.(*Command).execute(0xe81240, 0xc000093780, 0x1, 0x1, 0xe81240, 0xc000093780)
	/home/abo/gocode/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xe80b20, 0x43b54a, 0xe3ff60, 0xc000054750)
	/home/abo/gocode/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/abo/gocode/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/cellpointmobile/vk/cmd.Execute()
	/home/abo/sandbox/vk/cmd/root.go:51 +0x31
main.main()
	/home/abo/sandbox/vk/main.go:20 +0x20
```

To fix this issue need to update [VersionRegexp](https://github.com/cellpointmobile/vk-definitions/blob/master/vk-definitions.json#L536). I will raise PR.

**Comment by sanketg86** [comment]
PR raised https://github.com/cellpointmobile/vk-definitions/pull/7

**Comment by sanketg86** [comment]
Fixed
